### ISSUE TITLE
Event.get_body_soup() returns None even though body type is HTML

### ISSUE THREAD

**Issue by mbraakhekke** [O365/python-o365#1076]
I obtained some calendar events using `Calendar.get_events()`. The body type of the events is HTML but `Event.get_body_soup()` returns `None`. The reason is that `body_type` is `"html"` while `get_body_soup()` does a [case-sensitive comparison](https://github.com/O365/python-o365/blob/master/O365/calendar.py#L1596) against `"HTML"`.

Manually setting `body_type` to `"HTML"`, will result in the correct behavior of `get_body_soup()`.

**Comment by alejcas** [comment]
I think you are on older versions: 

This was fixed a long time ago:

`if self.body_type.upper() != 'HTML':`

**Comment by mbraakhekke** [comment]
Ah ok. I assumed that the master (which still does case-insensitive comparison; see the ref in my first post) has the latest version. I guess it does not.

**Comment by mbraakhekke** [comment]
I updated my O365 version to 2.0.34 but the problem persists. Reason: the fix @alejcas mentioned was made to the [`Message class`](https://github.com/O365/python-o365/blob/master/O365/message.py#L1052) but not to the [`Event class`](https://github.com/O365/python-o365/blob/master/O365/calendar.py#L1596).

**Comment by alejcas** [comment]
Fixed. Sorry I thought this was fixed!

**Comment by mbraakhekke** [comment]
No problem. Thanks!
